version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "my-rabbit"
    environment:
      RABBIT_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
      RABBITMQ_DEFAULT_USER: "ssafy"
      RABBITMQ_DEFAULT_PASS: "ssafy"
    ports:
      - "4672:5672"
      - "16672:15672"
      - "61613:61613"
    volumes:
      - ./etc/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - rabbit-data:/var/lib/rabbitmq/
      - rabbit-log:/var/log/rabbitmq/
#    entrypoint: ["rabbitmq-plugins", "enable", "rabbitmq_stomp"]
    restart: on-failure

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
    restart: on-failure

volumes:
  mongodb_data:
  rabbit-data:
  rabbit-log:
