spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url : jdbc:mariadb://localhost:3309/togeball
    url: jdbc:mariadb://i10a610.p.ssafy.io:3306/togeball
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
  config:
    import:
      - optional:properties/jpa.yml
      - optional:env/env.yml

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:3000/login/oauth2/code/google
#            redirect-uri: https://i10a610.p.ssafy.io/login/google
            authorization-grant-type: authorization_code
            scope: profile,email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: https://i10a610.p.ssafy.io/login/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080
  ssl:
    enabled: true
    enabled-protocols:
      - TLSv1.1
      - TLSv1.2
    key-store: "classpath:ssl/keystore.p12"
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: "PKCS12"

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: 10800000 # 3600000 : 60(분) * 60(초) * 1000 -> 1 시간
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh

rabbitmq:
  host: i10a610.p.ssafy.io
  port: 4672
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
  exchange: togeball.exchange
  chat:
    queue: chat.queue
    routing-key: togeball.chat
  notification:
    chat:
      queue: notification.chat.queue
    matching:
      queue: notification.matching.queue

cloud:
  aws:
    credentials:
      bucket-name: togeball-s3-bucket
      expiration: 3600000
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/**
